### ISSUE TITLE
Error installing opendds

### ISSUE THREAD

**Issue by xander-mbaka** [oci-labs/node-opendds#1]
Hi,

When i run npm install opendds im hit with the error:

`gyp: undefined variable lib_suffix in binding.gyp`

What am i not doing? please assist

**Comment by mitza-oci** [comment]
Please let us know which version of node and npm you have, which platform you are building on and which compiler you are building with.

Based on the error message it looks like there may have been a breaking change in gyp or node-gyp since this package was released.  Have you seen anything in those release notes or change logs that gives you a hint?

**Comment by xander-mbaka** [comment]
I run windows 8. Im running node v0.12.9, npm v2.14.9 and node-gyp v3.0.3. The error comes with the code ELIFECYCLE.

Here is a screenshot:
![untitled](https://cloud.githubusercontent.com/assets/525448/13601164/03fbc444-e53f-11e5-8fba-10556a81dba4.jpg)

Im under the impression that im missing some of the node-gyp dependencies as listed https://github.com/nodejs/node-gyp, but im not sure.

**Comment by mitza-oci** [comment]
According to https://github.com/nodejs/node-addon-examples (see README.md) even if we get past the gyp problems, this addon will not build because of the hugely breaking changes in Node and V8 since it was written for Node 0.8.  This can be resolved by using the NAN library (which I don't think even existed when we wrote the OpenDDS addon).  Let me know if you're interested in contributing this change.  It probably requires changes to OpenDDS proper as well.  If you're not going to contribute it then I will add it to the list of things to update, but I'm not sure when it will get done.

**Comment by xander-mbaka** [comment]
So an easier way to test the platform is to install node v0.8 in a sandbox? Ill do that get back to you.
Im also interested in contributing the change, how do i go about it (some nudge in the right direction would be appreciated)

**Comment by mitza-oci** [comment]
The exact versions I had working when this was first developed are:

- node-v0.8.18
- v8-3.16.4.2

Thanks for offering to help update it.  Take a look at that node-addon-examples repository I referenced last week.  I'm thinking we'll want to use the NAN library to have some isolation from the node/v8 versions.  There isn't all that much code in node-opendds to convert, but the code generated by opendds_idl will also have to change (see https://github.com/objectcomputing/OpenDDS/blob/master/dds/idl/v8_generator.cpp).  I will gladly assist with any issues you discover while working on this.

**Comment by mitza-oci** [comment]
See issue #4

**Comment by mitza-oci** [comment]
Issue #4 is fixed, this module is now working, at least on Linux.  It should work on Windows either directly or with minor changes.

**Comment by lygstate** [comment]
Still failed for nodejs 10 on Windows.
