### ISSUE TITLE
Consider using BigInt

### ISSUE THREAD

**Issue by Seairth** [oci-labs/node-opendds#23]
https://github.com/oci-labs/node-opendds/blob/062e1e24a5a53d5c18dcf69ae1cb570133301613/test/test_subscriber.js#L116

Noting the comment at the above line, you could probably use the new(ish) BigInt datatype which can be arbitrary large.

**Comment by mitza-oci** [comment]
The OMG DDS-JSON spec says these can be represented as JS strings to avoid truncation.  This might offer better compatibility than BigInt.

**Comment by simpsont-oci** [comment]
I think strings are probably the right path forward for this, but I want to double check what we're currently doing before closing this.

**Comment by iguessthislldo** [comment]
[`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) would allow actually using it as a number, so that seems like it'd be preferable to a string. We could support both and wouldn't even have to change the test because it looks the `BigInt` can compare to a string:

```js
BigInt("12379813738877118345") == "12379813738877118345"
true
BigInt("12379813738877118345") == "12379813738877118346"
false
```

**Comment by simpsont-oci** [comment]
BigInt is now supported (where supported by Node.js) after #52
