### ISSUE TITLE
build error with --security option

### ISSUE THREAD

**Issue by itsyaboyrooba** [oci-labs/node-opendds#33]
Hello!
`npm install --lib-suffix=d` fails when trying to install. The problem occurs when i use `--security` in the OpenDDS configuration. Everything works without `--security`.

CMD output:
[npm-install_error.txt](https://github.com/oci-labs/node-opendds/files/8168435/npm-install_error.txt)

npm logs:
[2022-03-02T09_26_40_960Z-debug.log](https://github.com/oci-labs/node-opendds/files/8168432/2022-03-02T09_26_40_960Z-debug.log)

My setenv:
[setenv.txt](https://github.com/oci-labs/node-opendds/files/8168481/setenv.txt)

- Windows_NT 10.0.19044
- node -v v10.22.1
- node-gyp -v v5.1.0
- Xerces 3.2.3
- OpenSSL 1.1.1
- MSVC v142 - VS 2019 C++ x64/x86

**Comment by iguessthislldo** [comment]
Could you specify what OpenDDS version or commit you're using? It might help make sense of the error messages and it reminds me of https://github.com/objectcomputing/OpenDDS/issues/3205 which got fixed in OpenDDS 3.19.0. Although the line numbers seem to be different part of the file than the part that was a problem in that issue. At the very least it looks like a something wrong like a unexpected macro replace is happening because those error messages make it seem like the compiler is struggling to parse the file.

**Comment by itsyaboyrooba** [comment]
> Could you specify what OpenDDS version or commit you're using? It might help make sense of the error messages and it reminds me of [objectcomputing/OpenDDS#3205](https://github.com/objectcomputing/OpenDDS/issues/3205) which got fixed in OpenDDS 3.19.0. Although the line numbers seem to be different part of the file than the part that was a problem in that issue. At the very least it looks like a something wrong like a unexpected macro replace is happening because those error messages make it seem like the compiler is struggling to parse the file.

i'm cloning the master branch.

**Comment by sanderkukk** [comment]
Thanks for the quick answer!

I built using openDDS master with all the versions listed above and can confirm it working.

Here, master is not used but checkout of `2550e2654208f1ce382b71ad8a0075b7f2152a8f` is made.
That checkout is used due to the weirdness of #20 
That was used to keep linux working. Now with the compilation of windows it seems that we need to move away from that checkout our resolve the #20.

I have not yet confirmed the build of windows having the same problem, maybe the more updated version of OpenDDS has fixed the issue (last master usage attempt was used the same date as the older issue). Or the problem is our side and now more then ever needs to be fixed.

Thanks

**Comment by sanderkukk** [comment]
Can confirm this particular issue as resolved.
