### ISSUE TITLE
Error when running test_publisher.js on Windows 10

### ISSUE THREAD

**Issue by devamaslan** [oci-labs/node-opendds#38]
Hello, I have built and installed node-opendds v0.1.1 on Windows 10 platform, and can run the cpp2node test case successfully. However, I get an exception with the test_publisher.js for both node2node and node2cpp, Process exited with code 3221226356, when the data writer attempts to register_instance for Sample1. Debugging this through into node-opendds.cpp, line 436 in register_instance is where it breaks: 
![RegisterInstanceException](https://user-images.githubusercontent.com/103411284/168303256-465f28f8-578b-4df9-9b08-d4d5e4e7d826.PNG)
![RegisterInstanceExceptionJs](https://user-images.githubusercontent.com/103411284/168303383-419aa552-5f18-473b-b189-6ebb697a95b3.PNG)

Details of dev environment:
Windows 10
Node v16.14.2
node-opendds-0.1.1
OpenDDS 3.19.0 using ACE 6.2a_p22
Visual Studio 2019 - all projects built for x64

**Comment by devamaslan** [comment]
I have updated to the OpenDDS-3.20 release and re-tried the tests, but the test_publisher.js is still failing with the same error.

**Comment by simpsont-oci** [comment]
A quick update here. I've started on adding Windows CI builds, which has been slightly more difficult than I expected, and in the process I found I was able to reproduce this issue on my local machine. Digging into it a bit further, it seems there is an issue with the way VS2019 (and possibly other VS compilers) handles the V8 serialization code. Specifically, the VS2019 code is throwing an exception in the virtual base destructor of std::istringstream after what appears to be legal usage, especially since gcc and clang do not have the same problem with the generated code. I don't have a final solution just yet, though I suspect it may require further modification of the build flags passed to the IDL library or to avoid std::istringstream entirely for the V8 code generation (which shouldn't be too painful if we migrate the V8 code generation over to use the new ValueReader and ValueWriter interfaces).

**Comment by devamaslan** [comment]
Thank you for providing this update. Are you able to give me a rough idea of when you think that a full solution might be available to resolve this issue?

**Comment by mitza-oci** [comment]
Here's part of the stack trace (with debugging symbols) when it crashes:
```
 	node.exe!std::ios_base::_Ios_base_dtor(std::ios_base * _This) Line 36
	NodeJSTestd.dll!std::basic_istringstream<char,std::char_traits<char>,std::allocator<char>>::`vbase destructor'()
 	NodeJSTestd.dll!OpenDDS::DCPS::copyFromV8(const v8::Local<v8::Object> & src, Mod::BasicTypes & out) Line 1327
```

We don't expect the standard library functions to be in node.exe.  They belong to `msvcp140d.dll` which is provided by the compiler (since it's the standard library, none of node's business).

So the answer to your question is "no" because we don't have a fix.  @simpsont-oci previously described a potential workaround but I don't know if we'd just hit another incompatibility along the way.  If you'd like to us to prioritize work on it, please consider commercial support https://objectcomputing.com/products/opendds/opendds-consulting-and-support
